//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace UcbWeb.Models
{
    public partial class IncidentUpdateEventModel : BaseModel
    {
    
        public virtual System.Guid Code
        {
            get { return _code; }
            set { _code = value; }
        }
        private System.Guid _code;
    
        public virtual string Type
        {
            get { return _type; }
            set { _type = value; }
        }
        private string _type;
    
        public virtual System.Guid IncidentCode
        {
            get { return _incidentCode; }
            set { _incidentCode = value; }
        }
        private System.Guid _incidentCode;
    
        public virtual System.DateTime DateTime
        {
            get { return _dateTime; }
            set { _dateTime = value; }
        }
        private System.DateTime _dateTime;
    
        public virtual string UpdateBy
        {
            get { return _updateBy; }
            set { _updateBy = value; }
        }
        private string _updateBy;
    
        public virtual byte[] RowIdentifier
        {
            get { return _rowIdentifier; }
            set { _rowIdentifier = value; }
        }
        private byte[] _rowIdentifier;
    }
}
