//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace UcbWeb.Models
{
    public partial class SiteSearchCriteriaModel
    {
    
        public virtual System.Guid OrganisationCode
        {
    	    get;
            set;
        }
    
        public virtual string Organisation
        {
    	    get;
            set;
        }
    
        public virtual string SiteName
        {
    	    get;
            set;
        }
    
        public virtual string PostCode
        {
    	    get;
            set;
        }
    }
}
