//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace UcbWeb.Models
{
    public partial class SiteStaffModel : BaseModel
    {
    
        public virtual System.Guid Code
        {
            get { return _code; }
            set { _code = value; }
        }
        private System.Guid _code;
    
        public virtual System.Guid SiteCode
        {
            get { return _siteCode; }
            set { _siteCode = value; }
        }
        private System.Guid _siteCode;
    
        public virtual System.Guid StaffCode
        {
            get { return _staffCode; }
            set { _staffCode = value; }
        }
        private System.Guid _staffCode;
    
        public virtual string Responsibility
        {
            get { return _responsibility; }
            set { _responsibility = value; }
        }
        private string _responsibility;
    
        public virtual byte[] RowIdentifier
        {
            get { return _rowIdentifier; }
            set { _rowIdentifier = value; }
        }
        private byte[] _rowIdentifier;
    }
}
