//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace UcbWeb.Models
{
    public partial class StaffSearchMatchModel
    {
    
        public virtual System.Guid Code
        {
    	    get;
            set;
        }
    
        public virtual string StaffNumber
        {
    	    get;
            set;
        }
    
        public virtual string LastName
        {
    	    get;
            set;
        }
    
        public virtual string FirstName
        {
    	    get;
            set;
        }
    
        public virtual System.Guid GradeCode
        {
    	    get;
            set;
        }
    
        public virtual string Grade
        {
    	    get;
            set;
        }
    
        public virtual bool IsActive
        {
    	    get;
            set;
        }
    }
}
