//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace UcbWeb.Models
{
    public partial class StaffAttributesModel : BaseModel
    {
    
        public virtual System.Guid Code
        {
            get { return _code; }
            set { _code = value; }
        }
        private System.Guid _code;
    
        public virtual System.Guid StaffCode
        {
            get { return _staffCode; }
            set { _staffCode = value; }
        }
        private System.Guid _staffCode;
    
        public virtual System.Guid ApplicationCode
        {
            get { return _applicationCode; }
            set { _applicationCode = value; }
        }
        private System.Guid _applicationCode;
    
        public virtual System.Guid ApplicationAttributeCode
        {
            get { return _applicationAttributeCode; }
            set { _applicationAttributeCode = value; }
        }
        private System.Guid _applicationAttributeCode;
    
        public virtual string LookupValue
        {
            get { return _lookupValue; }
            set { _lookupValue = value; }
        }
        private string _lookupValue;
    
        public virtual bool IsActive
        {
            get { return _isActive; }
            set { _isActive = value; }
        }
        private bool _isActive;
    
        public virtual byte[] RowIdentifier
        {
            get { return _rowIdentifier; }
            set { _rowIdentifier = value; }
        }
        private byte[] _rowIdentifier;
    }
}
