//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel;
using Dwp.Adep.Ucb.ResourceLibrary;
using AutoMapper;
using UcbWeb.Helpers;
using UcbWeb.ViewModels;
using UcbWeb.Models;
using UcbWeb.UcbService;


namespace UcbWeb.Controllers
{
    public partial class ADRoleLookupController : BaseController
    {

		private IUcbService UcbService;

		// Dependency Injection enabled constructors
        public ADRoleLookupController()
            : this(new UcbServiceClient(),new SessionManager(), new CacheManager())
        {
        }

        public ADRoleLookupController(IUcbService UcbService, ISessionManager sessionManager, ICacheManager cacheManager)
			:base(sessionManager,cacheManager)
        {
            this.UcbService = UcbService;
        }

		#region Edit
		
        // GET: /ADRoleLookup/Edit
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
        public ActionResult Edit()
        {
			// Retrieve ID from session
			string code = sessionManager.ADRoleLookupCode;
			
            ADRoleLookupVM model = new ADRoleLookupVM();
			
            // Not from staff or error
            if (String.IsNullOrEmpty(code))
            {
                //If session has lists then use them
                RepopulateListsFromCacheSession(model);

                //Assume we are in create mode as no code passed
                model.ADRoleLookupItem = new ADRoleLookupModel(){IsActive = true};
            }
            //if we have been passed a code then assume we are in edit situation and we need to retrieve from the database.
            else
            {
				// Create service instance
				IUcbService sc = UcbService;
				
                try
                {
					// Call service to get ADRoleLookup item and any associated lookups    
                    ADRoleLookupVMDC returnedObject = sc.GetADRoleLookup(CurrentUser, CurrentUser, appID, "", code);

					// Close service communication
					((ICommunicationObject)sc).Close();

                    //Get view model from service
                    model = ConvertADRoleLookupDC(returnedObject);

                    ResolveFieldCodesToFieldNamesUsingLists(model);

                    //Store the service version
                    sessionManager.ADRoleLookupServiceVersion = model.ADRoleLookupItem;
                }
				catch (Exception e)
				{
					// Handle the exception
					string message = ExceptionManager.HandleException(e, (ICommunicationObject)sc);
					model.Message = message;
					
					return View(model);
				}
            }

            //Adds current retrieved ADRoleLookup to session
            sessionManager.CurrentADRoleLookup = model.ADRoleLookupItem;
            SetAccessContext(model);
            
            return View(model);
        }    
		
		#endregion
		
		#region Create/Update

        // POST: /ADRoleLookup/Edit with Create button submitting
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult CreateADRoleLookup(FormCollection collection)
        {
            return UpdateADRoleLookup();
        }

        // POST: /ADRoleLookup/Edit with Save button submitting
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult SaveADRoleLookup(FormCollection collection)
        {
            return UpdateADRoleLookup();
        }

        //This method is shared between create and save
        private ActionResult UpdateADRoleLookup()
        {
			// Get the updated model
            var model = GetUpdatedModel();

			// Test to see if there are any errors
            var errors = ModelState
                    .Where(x => x.Value.Errors.Count > 0)
                    .Select(x => new { x.Key, x.Value.Errors[0].ErrorMessage })
                    .ToArray();
            
			//Set flags false
            SetFlagsFalse(model);
			
			// Test to see if the model has validated correctly
            if (ModelState.IsValid)
            {
				// Create service instance
				IUcbService sc = UcbService;
				
                //Attempt update
                try
                {
                    // Map model to data contract
                    ADRoleLookupDC ADRoleLookupItem = Mapper.Map<ADRoleLookupDC>(model.ADRoleLookupItem);

					ADRoleLookupVMDC returnedObject = null;

                    if (null == model.ADRoleLookupItem.Code || model.ADRoleLookupItem.Code == Guid.Empty)
                    {
						// Call service to create new ADRoleLookup item
                        returnedObject = sc.CreateADRoleLookup(CurrentUser, CurrentUser, appID, "", ADRoleLookupItem);
                    }
                    else
                    {
						// Call service to update ADRoleLookup item
                        returnedObject = sc.UpdateADRoleLookup(CurrentUser, CurrentUser, appID, "", ADRoleLookupItem);
                    }

					// Close service communication
					((ICommunicationObject)sc).Close();
					
					// Retrieve item returned by service
                    var createdADRoleLookup = returnedObject.ADRoleLookupItem;

					// Map data contract to model
                    model.ADRoleLookupItem = Mapper.Map<ADRoleLookupModel>(createdADRoleLookup);
					
                    //After creation some of the fields are display only so we need the resolved look up nmames
                    ResolveFieldCodesToFieldNamesUsingLists(model);

					// Set access context to Edit mode
                    model.AccessContext = ADRoleLookupAccessContext.Edit;

					// Save version of item returned by service into session
                    sessionManager.ADRoleLookupServiceVersion = model.ADRoleLookupItem;
                    sessionManager.CurrentADRoleLookup = model.ADRoleLookupItem;
                    
                    // Remove the state from the model as these are being populated by the controller and the HTML helpers are being populated with
					// the POSTED values and not the changed ones.
                    ModelState.Clear();
                    model.Message = Resources.MESSAGE_UPDATE_SUCCEEDED;
                }
				catch (Exception e)
				{
					// Handle the exception
					string message = ExceptionManager.HandleException(e, (ICommunicationObject)sc);
					model.Message = message;
					
					return View(model);
				}
            }

            return View(model);
        }

        #endregion
		
		#region Exit

        // POST: /ADRoleLookup/Edit with Exit button submitting
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult ExitADRoleLookup(FormCollection collection)
        {
            var model = GetUpdatedModel();
            if (model.IsExitConfirmed == "True" || !model.IsViewDirty)
            {
                //Set flags false
                SetFlagsFalse(model);

                model.IsExitConfirmed = "False";
                
                //remove the current values from session
                sessionManager.CurrentADRoleLookup = null;
                sessionManager.ADRoleLookupServiceVersion = null;

                return RedirectToAction("Search", "ADRoleLookup");
                
            }
            else
            {
                //Set flags false
                SetFlagsFalse(model);
                model.Message = Resources.MESSAGE_EXITCONFIRMATION;
                model.IsExitConfirmed = "True";
            }
            
            return View(model);
        }
		
		#endregion
		
		#region Delete

        // POST: /ADRoleLookup/Edit with Delete button submitting
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult DeleteADRoleLookup(FormCollection collection)
        {
            var model = GetUpdatedModel();
            if (model.IsDeleteConfirmed == "True")
            {
                //Set flags false
                SetFlagsFalse(model);
            
                model.IsDeleteConfirmed = "False";
				
				// Create service instance
				IUcbService sc = UcbService;
				
                try
                {
					// Call service to delete the item
                    sc.DeleteADRoleLookup(CurrentUser, CurrentUser, appID, "", model.ADRoleLookupItem.Code.ToString(), model.ADRoleLookupItem.RowIdentifier.ToString());

					// Close service communication
					((ICommunicationObject)sc).Close();
					
                    // Remove the current values from session
                    sessionManager.CurrentADRoleLookup = null;
                    sessionManager.ADRoleLookupServiceVersion = null;

                    // Remove the state from the model as these are being populated by the controller and the HTML helpers are being populated with
					// the POSTED values and not the changed ones.
                    ModelState.Clear();
					
					// Create new item but keep any lists
					model.ADRoleLookupItem = new ADRoleLookupModel(){IsActive = true};
					
					// Set message to return to user
                    model.Message = Resources.MESSAGE_DELETE_SUCCEEDED;
					
					// Set access context to Edit mode
                    model.AccessContext = ADRoleLookupAccessContext.Create;
					
					// Redirect to the search screen
                    return View(model);
                }
				catch (Exception e)
                {
					// Handle the exception
					string message = ExceptionManager.HandleException(e, (ICommunicationObject)sc);
					model.Message = message;
					
					return View(model);
                }
            }
            else
            {
                //Set flags false
                SetFlagsFalse(model);
                model.Message = Resources.MESSAGE_DELETECONFIRMATION;
                model.IsDeleteConfirmed = "True";
            }
            
            return View(model);
        }
		
		#endregion
		
		#region New

        // POST: /ADRoleLookup/Edit with New button submitting
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
        [HttpParamSearch(Prefix = "Search::")]
        [HttpPost]
        public ActionResult NewADRoleLookup(FormCollection collection)
        {
            var model = GetUpdatedModel();
            //Set flags false
            SetFlagsFalse(model);
            
            //Clear Down Session
			sessionManager.ADRoleLookupCode = null;
            sessionManager.CurrentADRoleLookup = null;
            sessionManager.ADRoleLookupServiceVersion = null;
            
            //Go to the Edit Screen
            return RedirectToAction("Edit", "ADRoleLookup");
        }
		
		#endregion

		#region Search

        // GET: /ADRoleLookup/Search
        //This is called when first entering search ADRoleLookup screen or when paging
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
        public ActionResult Search(int page = 1)
        {   
			// Create service instance
			IUcbService sc = UcbService;
			
			// Create model
			ADRoleLookupSearchVM model = new ADRoleLookupSearchVM();
			
			try
			{
				ADRoleLookupSearchVMDC response = sc.SearchADRoleLookup(CurrentUser, CurrentUser, appID, "", null, page, PageSize, true);

				// Close service communication
				((ICommunicationObject)sc).Close();

				//Map response back to view model
				model.MatchList = Mapper.Map<IEnumerable<ADRoleLookupSearchMatchDC>, List<ADRoleLookupSearchMatchModel>>(response.MatchList);

				// Set paging values
				model.TotalRows = response.RecordCount;
				model.PageSize = sessionManager.PageSize;
				model.PageNumber = page;
				
				// Store the page number we were on
				sessionManager.ADRoleLookupPageNumber = model.PageNumber;
	        
				return View(model);
			}
			catch (Exception e)
			{
				// Handle the exception
				string message = ExceptionManager.HandleException(e, (ICommunicationObject)sc);
				model.Message = message;
				
				return View(model);
			}

        }

        // POST: /ADRoleLookup/Search
        //This is called when clicking search button
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
		[HttpParamSearch(Prefix = "Search::")]
        [HttpPost]
        public ActionResult SearchPost(ADRoleLookupSearchVM model, int page = 1)
        {
		
			// Iterate through form keys
            foreach (string Key in Request.Form.Keys)
            {
				// Test if Select button was clicked...
                if (Key.StartsWith("Search::SearchPost_"))
                {
					// Retrieve ID for entity which was selected
                    Guid Value = Guid.Parse(Key.Substring(19));
									
					// Store ID for Edit screen
					sessionManager.ADRoleLookupCode = Value.ToString();
					
					// Call out to Edit screen
                    return RedirectToAction("Edit", "ADRoleLookup", new { code = Value });

                }
            }

            // Return to the Screen
            return View(model);
        }

        #endregion
		
		#region Private methods
		
        private void SetFlagsFalse(ADRoleLookupVM model)
        {
            model.IsDeleteConfirmed = "False";
            model.IsExitConfirmed = "False";
            model.IsNewConfirmed = "False";

            //Stop the binder resetting the posted values
            ModelState.Remove("IsDeleteConfirmed");
            ModelState.Remove("IsExitConfirmed");
            ModelState.Remove("IsNewConfirmed");
        }

        private void ResolveFieldCodesToFieldNamesUsingLists(ADRoleLookupVM model)
        {
			//TODO:
        }

        /// <summary>
        /// Private method to merge in the model 
        /// </summary>
        /// <returns></returns>
        private ADRoleLookupVM GetUpdatedModel()
        {
            ADRoleLookupVM model = new ADRoleLookupVM();
            RepopulateListsFromCacheSession(model);
            model.Message = "";

            if (sessionManager.CurrentADRoleLookup != null)
            {
                model.ADRoleLookupItem = sessionManager.CurrentADRoleLookup;
            }

            //***************************************NEED WHITE LIST ---- BLACK LIST ------ TO PREVENT OVERPOSTING **************************
            bool result = TryUpdateModel(model);//This also validates and sets ModelState
            //*******************************************************************************************************************************
            if (sessionManager.CurrentADRoleLookup != null)
            {
                //*****************************************PREVENT OVER POSTING ATTACKS******************************************************
                //Get the values for read only fields from session
                MergeNewValuesWithOriginal(model.ADRoleLookupItem);
                //***************************************************************************************************************************
            }

            SetAccessContext(model);

            return model;
        }
		
        private ADRoleLookupVM ConvertADRoleLookupDC(ADRoleLookupVMDC returnedObject)
        {
            ADRoleLookupVM model = new ADRoleLookupVM();
            
			// Map ADRoleLookup Item
			model.ADRoleLookupItem = Mapper.Map<ADRoleLookupDC, ADRoleLookupModel>(returnedObject.ADRoleLookupItem);
            
			// Map lookup data lists
			model.RoleList = Mapper.Map<IEnumerable<RoleDC>, List<RoleModel>>(returnedObject.RoleList);
        
            return model;
        }
		
		private void RepopulateListsFromCacheSession(ADRoleLookupVM model)
        {
			// Populate cached lists if they are empty. Will invoke service call
            ADRoleLookupLookupListsCacheObject CachedLists = cacheManager.ADRoleLookupListCache;

			// Retrieve any cached lists to model
			model.RoleList = CachedLists.RoleList;
   
        }

        private void MergeNewValuesWithOriginal(ADRoleLookupModel modelFromView)
        {
            //***************************The values that are display only will not be posted back so need to get them from session**************************

            ADRoleLookupModel OriginalValuesFromSession = sessionManager.CurrentADRoleLookup;

        }
		
		private void SetAccessContext(ADRoleLookupVM model)
        {
            //Decide on access context
            if (null == model.ADRoleLookupItem || model.ADRoleLookupItem.Code == Guid.Empty)
            {
				// Create context
                model.AccessContext = ADRoleLookupAccessContext.Create;
            }
            else
            {
				// Edit context
                model.AccessContext = ADRoleLookupAccessContext.Edit;
            }
        }
		
		private void DetermineIsDirty(ADRoleLookupVM model)
        {
            //Compare the ADRoleLookup to the original session
            if (model.ADRoleLookupItem.PublicInstancePropertiesEqual(sessionManager.ADRoleLookupServiceVersion, "RowIdentifier"))
            {
                model.IsViewDirty = false;
            }
            else
            {
                model.IsViewDirty = true;
            }

        }
        #endregion
       
    }
}
