//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel;
using Dwp.Adep.Ucb.ResourceLibrary;
using AutoMapper;
using UcbWeb.Helpers;
using UcbWeb.ViewModels;
using UcbWeb.Models;
using UcbWeb.UcbService;


namespace UcbWeb.Controllers
{
    public partial class IncidentSystemMarkedController : BaseController
    {

		private IUcbService UcbService;

		// Dependency Injection enabled constructors
        public IncidentSystemMarkedController()
            : this(new UcbServiceClient(),new SessionManager(), new CacheManager())
        {
        }

        public IncidentSystemMarkedController(IUcbService UcbService, ISessionManager sessionManager, ICacheManager cacheManager)
			:base(sessionManager,cacheManager)
        {
            this.UcbService = UcbService;
        }

		#region Edit
		
        // GET: /IncidentSystemMarked/Edit
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
        public ActionResult Edit()
        {
			// Retrieve ID from session
			string code = sessionManager.IncidentSystemMarkedCode;
			
            IncidentSystemMarkedVM model = new IncidentSystemMarkedVM();
			
            // Not from staff or error
            if (String.IsNullOrEmpty(code))
            {
                //If session has lists then use them
                RepopulateListsFromCacheSession(model);

                //Assume we are in create mode as no code passed
                model.IncidentSystemMarkedItem = new IncidentSystemMarkedModel();
            }
            //if we have been passed a code then assume we are in edit situation and we need to retrieve from the database.
            else
            {
				// Create service instance
				IUcbService sc = UcbService;
				
                try
                {
					// Call service to get IncidentSystemMarked item and any associated lookups    
                    IncidentSystemMarkedVMDC returnedObject = sc.GetIncidentSystemMarked(CurrentUser, CurrentUser, appID, "", code);

					// Close service communication
					((ICommunicationObject)sc).Close();

                    //Get view model from service
                    model = ConvertIncidentSystemMarkedDC(returnedObject);

                    ResolveFieldCodesToFieldNamesUsingLists(model);

                    //Store the service version
                    sessionManager.IncidentSystemMarkedServiceVersion = model.IncidentSystemMarkedItem;
                }
				catch (Exception e)
				{
					// Handle the exception
					string message = ExceptionManager.HandleException(e, (ICommunicationObject)sc);
					model.Message = message;
					
					return View(model);
				}
            }

            //Adds current retrieved IncidentSystemMarked to session
            sessionManager.CurrentIncidentSystemMarked = model.IncidentSystemMarkedItem;
            SetAccessContext(model);
            
            return View(model);
        }    
		
		#endregion
		
		#region Create/Update

        // POST: /IncidentSystemMarked/Edit with Create button submitting
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult CreateIncidentSystemMarked(FormCollection collection)
        {
            return UpdateIncidentSystemMarked();
        }

        // POST: /IncidentSystemMarked/Edit with Save button submitting
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult SaveIncidentSystemMarked(FormCollection collection)
        {
            return UpdateIncidentSystemMarked();
        }

        //This method is shared between create and save
        private ActionResult UpdateIncidentSystemMarked()
        {
			// Get the updated model
            var model = GetUpdatedModel();

			// Test to see if there are any errors
            var errors = ModelState
                    .Where(x => x.Value.Errors.Count > 0)
                    .Select(x => new { x.Key, x.Value.Errors[0].ErrorMessage })
                    .ToArray();
            
			//Set flags false
            SetFlagsFalse(model);
			
			// Test to see if the model has validated correctly
            if (ModelState.IsValid)
            {
				// Create service instance
				IUcbService sc = UcbService;
				
                //Attempt update
                try
                {
                    // Map model to data contract
                    IncidentSystemMarkedDC IncidentSystemMarkedItem = Mapper.Map<IncidentSystemMarkedDC>(model.IncidentSystemMarkedItem);

					IncidentSystemMarkedVMDC returnedObject = null;

                    if (null == model.IncidentSystemMarkedItem.Code || model.IncidentSystemMarkedItem.Code == Guid.Empty)
                    {
						// Call service to create new IncidentSystemMarked item
                        returnedObject = sc.CreateIncidentSystemMarked(CurrentUser, CurrentUser, appID, "", IncidentSystemMarkedItem);
                    }
                    else
                    {
						// Call service to update IncidentSystemMarked item
                        returnedObject = sc.UpdateIncidentSystemMarked(CurrentUser, CurrentUser, appID, "", IncidentSystemMarkedItem);
                    }

					// Close service communication
					((ICommunicationObject)sc).Close();
					
					// Retrieve item returned by service
                    var createdIncidentSystemMarked = returnedObject.IncidentSystemMarkedItem;

					// Map data contract to model
                    model.IncidentSystemMarkedItem = Mapper.Map<IncidentSystemMarkedModel>(createdIncidentSystemMarked);
					
                    //After creation some of the fields are display only so we need the resolved look up nmames
                    ResolveFieldCodesToFieldNamesUsingLists(model);

					// Set access context to Edit mode
                    model.AccessContext = IncidentSystemMarkedAccessContext.Edit;

					// Save version of item returned by service into session
                    sessionManager.IncidentSystemMarkedServiceVersion = model.IncidentSystemMarkedItem;
                    sessionManager.CurrentIncidentSystemMarked = model.IncidentSystemMarkedItem;
                    
                    // Remove the state from the model as these are being populated by the controller and the HTML helpers are being populated with
					// the POSTED values and not the changed ones.
                    ModelState.Clear();
                    model.Message = Resources.MESSAGE_UPDATE_SUCCEEDED;
                }
				catch (Exception e)
				{
					// Handle the exception
					string message = ExceptionManager.HandleException(e, (ICommunicationObject)sc);
					model.Message = message;
					
					return View(model);
				}
            }

            return View(model);
        }

        #endregion
		
		#region Exit

        // POST: /IncidentSystemMarked/Edit with Exit button submitting
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult ExitIncidentSystemMarked(FormCollection collection)
        {
            var model = GetUpdatedModel();
            if (model.IsExitConfirmed == "True" || !model.IsViewDirty)
            {
                //Set flags false
                SetFlagsFalse(model);

                model.IsExitConfirmed = "False";
                
                //remove the current values from session
                sessionManager.CurrentIncidentSystemMarked = null;
                sessionManager.IncidentSystemMarkedServiceVersion = null;

                return RedirectToAction("Search", "IncidentSystemMarked");
                
            }
            else
            {
                //Set flags false
                SetFlagsFalse(model);
                model.Message = Resources.MESSAGE_EXITCONFIRMATION;
                model.IsExitConfirmed = "True";
            }
            
            return View(model);
        }
		
		#endregion
		
		#region Delete

        // POST: /IncidentSystemMarked/Edit with Delete button submitting
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult DeleteIncidentSystemMarked(FormCollection collection)
        {
            var model = GetUpdatedModel();
            if (model.IsDeleteConfirmed == "True")
            {
                //Set flags false
                SetFlagsFalse(model);
            
                model.IsDeleteConfirmed = "False";
				
				// Create service instance
				IUcbService sc = UcbService;
				
                try
                {
					// Call service to delete the item
                    sc.DeleteIncidentSystemMarked(CurrentUser, CurrentUser, appID, "", model.IncidentSystemMarkedItem.Code.ToString(), model.IncidentSystemMarkedItem.RowIdentifier.ToString());

					// Close service communication
					((ICommunicationObject)sc).Close();
					
                    // Remove the current values from session
                    sessionManager.CurrentIncidentSystemMarked = null;
                    sessionManager.IncidentSystemMarkedServiceVersion = null;

                    // Remove the state from the model as these are being populated by the controller and the HTML helpers are being populated with
					// the POSTED values and not the changed ones.
                    ModelState.Clear();
					
					// Create new item but keep any lists
					model.IncidentSystemMarkedItem = new IncidentSystemMarkedModel();
					
					// Set message to return to user
                    model.Message = Resources.MESSAGE_DELETE_SUCCEEDED;
					
					// Set access context to Edit mode
                    model.AccessContext = IncidentSystemMarkedAccessContext.Create;
					
					// Redirect to the search screen
                    return View(model);
                }
				catch (Exception e)
                {
					// Handle the exception
					string message = ExceptionManager.HandleException(e, (ICommunicationObject)sc);
					model.Message = message;
					
					return View(model);
                }
            }
            else
            {
                //Set flags false
                SetFlagsFalse(model);
                model.Message = Resources.MESSAGE_DELETECONFIRMATION;
                model.IsDeleteConfirmed = "True";
            }
            
            return View(model);
        }
		
		#endregion
		
		#region New

        // POST: /IncidentSystemMarked/Edit with New button submitting
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
        [HttpParamSearch(Prefix = "Search::")]
        [HttpPost]
        public ActionResult NewIncidentSystemMarked(FormCollection collection)
        {
            var model = GetUpdatedModel();
            //Set flags false
            SetFlagsFalse(model);
            
            //Clear Down Session
			sessionManager.IncidentSystemMarkedCode = null;
            sessionManager.CurrentIncidentSystemMarked = null;
            sessionManager.IncidentSystemMarkedServiceVersion = null;
            
            //Go to the Edit Screen
            return RedirectToAction("Edit", "IncidentSystemMarked");
        }
		
		#endregion

		#region Search

        // GET: /IncidentSystemMarked/Search
        //This is called when first entering search IncidentSystemMarked screen or when paging
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
        public ActionResult Search(int page = 1)
        {   
			// Create service instance
			IUcbService sc = UcbService;
			
			// Create model
			IncidentSystemMarkedSearchVM model = new IncidentSystemMarkedSearchVM();
			
			try
			{
				IncidentSystemMarkedSearchVMDC response = sc.SearchIncidentSystemMarked(CurrentUser, CurrentUser, appID, "", null, page, PageSize);

				// Close service communication
				((ICommunicationObject)sc).Close();

				//Map response back to view model
				model.MatchList = Mapper.Map<IEnumerable<IncidentSystemMarkedSearchMatchDC>, List<IncidentSystemMarkedSearchMatchModel>>(response.MatchList);

				// Set paging values
				model.TotalRows = response.RecordCount;
				model.PageSize = sessionManager.PageSize;
				model.PageNumber = page;
				
				// Store the page number we were on
				sessionManager.IncidentSystemMarkedPageNumber = model.PageNumber;
	        
				return View(model);
			}
			catch (Exception e)
			{
				// Handle the exception
				string message = ExceptionManager.HandleException(e, (ICommunicationObject)sc);
				model.Message = message;
				
				return View(model);
			}

        }

        // POST: /IncidentSystemMarked/Search
        //This is called when clicking search button
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
		[HttpParamSearch(Prefix = "Search::")]
        [HttpPost]
        public ActionResult SearchPost(IncidentSystemMarkedSearchVM model, int page = 1)
        {
		
			// Iterate through form keys
            foreach (string Key in Request.Form.Keys)
            {
				// Test if Select button was clicked...
                if (Key.StartsWith("Search::SearchPost_"))
                {
					// Retrieve ID for entity which was selected
                    Guid Value = Guid.Parse(Key.Substring(19));
									
					// Store ID for Edit screen
					sessionManager.IncidentSystemMarkedCode = Value.ToString();
					
					// Call out to Edit screen
                    return RedirectToAction("Edit", "IncidentSystemMarked", new { code = Value });

                }
            }

            // Return to the Screen
            return View(model);
        }

        #endregion
		
		#region Private methods
		
        private void SetFlagsFalse(IncidentSystemMarkedVM model)
        {
            model.IsDeleteConfirmed = "False";
            model.IsExitConfirmed = "False";
            model.IsNewConfirmed = "False";

            //Stop the binder resetting the posted values
            ModelState.Remove("IsDeleteConfirmed");
            ModelState.Remove("IsExitConfirmed");
            ModelState.Remove("IsNewConfirmed");
        }

        private void ResolveFieldCodesToFieldNamesUsingLists(IncidentSystemMarkedVM model)
        {
			//TODO:
        }

        /// <summary>
        /// Private method to merge in the model 
        /// </summary>
        /// <returns></returns>
        private IncidentSystemMarkedVM GetUpdatedModel()
        {
            IncidentSystemMarkedVM model = new IncidentSystemMarkedVM();
            RepopulateListsFromCacheSession(model);
            model.Message = "";

            if (sessionManager.CurrentIncidentSystemMarked != null)
            {
                model.IncidentSystemMarkedItem = sessionManager.CurrentIncidentSystemMarked;
            }

            //***************************************NEED WHITE LIST ---- BLACK LIST ------ TO PREVENT OVERPOSTING **************************
            bool result = TryUpdateModel(model);//This also validates and sets ModelState
            //*******************************************************************************************************************************
            if (sessionManager.CurrentIncidentSystemMarked != null)
            {
                //*****************************************PREVENT OVER POSTING ATTACKS******************************************************
                //Get the values for read only fields from session
                MergeNewValuesWithOriginal(model.IncidentSystemMarkedItem);
                //***************************************************************************************************************************
            }

            SetAccessContext(model);

            return model;
        }
		
        private IncidentSystemMarkedVM ConvertIncidentSystemMarkedDC(IncidentSystemMarkedVMDC returnedObject)
        {
            IncidentSystemMarkedVM model = new IncidentSystemMarkedVM();
            
			// Map IncidentSystemMarked Item
			model.IncidentSystemMarkedItem = Mapper.Map<IncidentSystemMarkedDC, IncidentSystemMarkedModel>(returnedObject.IncidentSystemMarkedItem);
            
			// Map lookup data lists
			model.IncidentList = Mapper.Map<IEnumerable<IncidentDC>, List<IncidentModel>>(returnedObject.IncidentList);
			model.SystemMarkedList = Mapper.Map<IEnumerable<SystemMarkedDC>, List<SystemMarkedModel>>(returnedObject.SystemMarkedList);
        
            return model;
        }
		
		private void RepopulateListsFromCacheSession(IncidentSystemMarkedVM model)
        {
			// Populate cached lists if they are empty. Will invoke service call
            IncidentSystemMarkedLookupListsCacheObject CachedLists = cacheManager.IncidentSystemMarkedListCache;

			// Retrieve any cached lists to model
			model.IncidentList = CachedLists.IncidentList;
			model.SystemMarkedList = CachedLists.SystemMarkedList;
   
        }

        private void MergeNewValuesWithOriginal(IncidentSystemMarkedModel modelFromView)
        {
            //***************************The values that are display only will not be posted back so need to get them from session**************************

            IncidentSystemMarkedModel OriginalValuesFromSession = sessionManager.CurrentIncidentSystemMarked;

        }
		
		private void SetAccessContext(IncidentSystemMarkedVM model)
        {
            //Decide on access context
            if (null == model.IncidentSystemMarkedItem || model.IncidentSystemMarkedItem.Code == Guid.Empty)
            {
				// Create context
                model.AccessContext = IncidentSystemMarkedAccessContext.Create;
            }
            else
            {
				// Edit context
                model.AccessContext = IncidentSystemMarkedAccessContext.Edit;
            }
        }
		
		private void DetermineIsDirty(IncidentSystemMarkedVM model)
        {
            //Compare the IncidentSystemMarked to the original session
            if (model.IncidentSystemMarkedItem.PublicInstancePropertiesEqual(sessionManager.IncidentSystemMarkedServiceVersion, "RowIdentifier"))
            {
                model.IsViewDirty = false;
            }
            else
            {
                model.IsViewDirty = true;
            }

        }
        #endregion
       
    }
}
