//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel;
using Dwp.Adep.Ucb.ResourceLibrary;
using AutoMapper;
using UcbWeb.Helpers;
using UcbWeb.ViewModels;
using UcbWeb.Models;
using UcbWeb.UcbService;


namespace UcbWeb.Controllers
{
    public partial class SystemParameterController : BaseController
    {

		private IUcbService UcbService;

		// Dependency Injection enabled constructors
        public SystemParameterController()
            : this(new UcbServiceClient(),new SessionManager(), new CacheManager())
        {
        }

        public SystemParameterController(IUcbService UcbService, ISessionManager sessionManager, ICacheManager cacheManager)
			:base(sessionManager,cacheManager)
        {
            this.UcbService = UcbService;
        }

		#region Edit
		
        // GET: /SystemParameter/Edit
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
        public ActionResult Edit()
        {
			// Retrieve ID from session
			string code = sessionManager.SystemParameterCode;
			
            SystemParameterVM model = new SystemParameterVM();
			
            // Not from staff or error
            if (String.IsNullOrEmpty(code))
            {
                //If session has lists then use them
                RepopulateListsFromCacheSession(model);

                //Assume we are in create mode as no code passed
                model.SystemParameterItem = new SystemParameterModel();
            }
            //if we have been passed a code then assume we are in edit situation and we need to retrieve from the database.
            else
            {
				// Create service instance
				IUcbService sc = UcbService;
				
                try
                {
					// Call service to get SystemParameter item and any associated lookups    
                    SystemParameterVMDC returnedObject = sc.GetSystemParameter(CurrentUser, CurrentUser, appID, "", code);

					// Close service communication
					((ICommunicationObject)sc).Close();

                    //Get view model from service
                    model = ConvertSystemParameterDC(returnedObject);

                    ResolveFieldCodesToFieldNamesUsingLists(model);

                    //Store the service version
                    sessionManager.SystemParameterServiceVersion = model.SystemParameterItem;
                }
				catch (Exception e)
				{
					// Handle the exception
					string message = ExceptionManager.HandleException(e, (ICommunicationObject)sc);
					model.Message = message;
					
					return View(model);
				}
            }

            //Adds current retrieved SystemParameter to session
            sessionManager.CurrentSystemParameter = model.SystemParameterItem;
            SetAccessContext(model);
            
            return View(model);
        }    
		
		#endregion
		
		#region Create/Update

        // POST: /SystemParameter/Edit with Create button submitting
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult CreateSystemParameter(FormCollection collection)
        {
            return UpdateSystemParameter();
        }

        // POST: /SystemParameter/Edit with Save button submitting
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult SaveSystemParameter(FormCollection collection)
        {
            return UpdateSystemParameter();
        }

        //This method is shared between create and save
        private ActionResult UpdateSystemParameter()
        {
			// Get the updated model
            var model = GetUpdatedModel();

			// Test to see if there are any errors
            var errors = ModelState
                    .Where(x => x.Value.Errors.Count > 0)
                    .Select(x => new { x.Key, x.Value.Errors[0].ErrorMessage })
                    .ToArray();
            
			//Set flags false
            SetFlagsFalse(model);
			
			// Test to see if the model has validated correctly
            if (ModelState.IsValid)
            {
				// Create service instance
				IUcbService sc = UcbService;
				
                //Attempt update
                try
                {
                    // Map model to data contract
                    SystemParameterDC SystemParameterItem = Mapper.Map<SystemParameterDC>(model.SystemParameterItem);

					SystemParameterVMDC returnedObject = null;

                    if (null == model.SystemParameterItem.Code || model.SystemParameterItem.Code == Guid.Empty)
                    {
						// Call service to create new SystemParameter item
                        returnedObject = sc.CreateSystemParameter(CurrentUser, CurrentUser, appID, "", SystemParameterItem);
                    }
                    else
                    {
						// Call service to update SystemParameter item
                        returnedObject = sc.UpdateSystemParameter(CurrentUser, CurrentUser, appID, "", SystemParameterItem);
                    }

					// Close service communication
					((ICommunicationObject)sc).Close();
					
					// Retrieve item returned by service
                    var createdSystemParameter = returnedObject.SystemParameterItem;

					// Map data contract to model
                    model.SystemParameterItem = Mapper.Map<SystemParameterModel>(createdSystemParameter);
					
                    //After creation some of the fields are display only so we need the resolved look up nmames
                    ResolveFieldCodesToFieldNamesUsingLists(model);

					// Set access context to Edit mode
                    model.AccessContext = SystemParameterAccessContext.Edit;

					// Save version of item returned by service into session
                    sessionManager.SystemParameterServiceVersion = model.SystemParameterItem;
                    sessionManager.CurrentSystemParameter = model.SystemParameterItem;
                    
                    // Remove the state from the model as these are being populated by the controller and the HTML helpers are being populated with
					// the POSTED values and not the changed ones.
                    ModelState.Clear();
                    model.Message = Resources.MESSAGE_UPDATE_SUCCEEDED;
                }
				catch (Exception e)
				{
					// Handle the exception
					string message = ExceptionManager.HandleException(e, (ICommunicationObject)sc);
					model.Message = message;
					
					return View(model);
				}
            }

            return View(model);
        }

        #endregion
		
		#region Exit

        // POST: /SystemParameter/Edit with Exit button submitting
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult ExitSystemParameter(FormCollection collection)
        {
            var model = GetUpdatedModel();
            if (model.IsExitConfirmed == "True" || !model.IsViewDirty)
            {
                //Set flags false
                SetFlagsFalse(model);

                model.IsExitConfirmed = "False";
                
                //remove the current values from session
                sessionManager.CurrentSystemParameter = null;
                sessionManager.SystemParameterServiceVersion = null;

                return RedirectToAction("Search", "SystemParameter");
                
            }
            else
            {
                //Set flags false
                SetFlagsFalse(model);
                model.Message = Resources.MESSAGE_EXITCONFIRMATION;
                model.IsExitConfirmed = "True";
            }
            
            return View(model);
        }
		
		#endregion
		
		#region Delete

        // POST: /SystemParameter/Edit with Delete button submitting
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult DeleteSystemParameter(FormCollection collection)
        {
            var model = GetUpdatedModel();
            if (model.IsDeleteConfirmed == "True")
            {
                //Set flags false
                SetFlagsFalse(model);
            
                model.IsDeleteConfirmed = "False";
				
				// Create service instance
				IUcbService sc = UcbService;
				
                try
                {
					// Call service to delete the item
                    sc.DeleteSystemParameter(CurrentUser, CurrentUser, appID, "", model.SystemParameterItem.Code.ToString(), model.SystemParameterItem.RowIdentifier.ToString());

					// Close service communication
					((ICommunicationObject)sc).Close();
					
                    // Remove the current values from session
                    sessionManager.CurrentSystemParameter = null;
                    sessionManager.SystemParameterServiceVersion = null;

                    // Remove the state from the model as these are being populated by the controller and the HTML helpers are being populated with
					// the POSTED values and not the changed ones.
                    ModelState.Clear();
					
					// Create new item but keep any lists
					model.SystemParameterItem = new SystemParameterModel();
					
					// Set message to return to user
                    model.Message = Resources.MESSAGE_DELETE_SUCCEEDED;
					
					// Set access context to Edit mode
                    model.AccessContext = SystemParameterAccessContext.Create;
					
					// Redirect to the search screen
                    return View(model);
                }
				catch (Exception e)
                {
					// Handle the exception
					string message = ExceptionManager.HandleException(e, (ICommunicationObject)sc);
					model.Message = message;
					
					return View(model);
                }
            }
            else
            {
                //Set flags false
                SetFlagsFalse(model);
                model.Message = Resources.MESSAGE_DELETECONFIRMATION;
                model.IsDeleteConfirmed = "True";
            }
            
            return View(model);
        }
		
		#endregion
		
		#region New

        // POST: /SystemParameter/Edit with New button submitting
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
        [HttpParamSearch(Prefix = "Search::")]
        [HttpPost]
        public ActionResult NewSystemParameter(FormCollection collection)
        {
            var model = GetUpdatedModel();
            //Set flags false
            SetFlagsFalse(model);
            
            //Clear Down Session
			sessionManager.SystemParameterCode = null;
            sessionManager.CurrentSystemParameter = null;
            sessionManager.SystemParameterServiceVersion = null;
            
            //Go to the Edit Screen
            return RedirectToAction("Edit", "SystemParameter");
        }
		
		#endregion

		#region Search

        // GET: /SystemParameter/Search
        //This is called when first entering search SystemParameter screen or when paging
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
        public ActionResult Search(int page = 1)
        {   
			// Create service instance
			IUcbService sc = UcbService;
			
			// Create model
			SystemParameterSearchVM model = new SystemParameterSearchVM();
			
			try
			{
				SystemParameterSearchVMDC response = sc.SearchSystemParameter(CurrentUser, CurrentUser, appID, "", null, page, PageSize);

				// Close service communication
				((ICommunicationObject)sc).Close();

				//Map response back to view model
				model.MatchList = Mapper.Map<IEnumerable<SystemParameterSearchMatchDC>, List<SystemParameterSearchMatchModel>>(response.MatchList);

				// Set paging values
				model.TotalRows = response.RecordCount;
				model.PageSize = sessionManager.PageSize;
				model.PageNumber = page;
				
				// Store the page number we were on
				sessionManager.SystemParameterPageNumber = model.PageNumber;
	        
				return View(model);
			}
			catch (Exception e)
			{
				// Handle the exception
				string message = ExceptionManager.HandleException(e, (ICommunicationObject)sc);
				model.Message = message;
				
				return View(model);
			}

        }

        // POST: /SystemParameter/Search
        //This is called when clicking search button
		[CustomAuthorize(Roles = AppRoles.ADMIN)]
		[HttpParamSearch(Prefix = "Search::")]
        [HttpPost]
        public ActionResult SearchPost(SystemParameterSearchVM model, int page = 1)
        {
		
			// Iterate through form keys
            foreach (string Key in Request.Form.Keys)
            {
				// Test if Select button was clicked...
                if (Key.StartsWith("Search::SearchPost_"))
                {
					// Retrieve ID for entity which was selected
                    Guid Value = Guid.Parse(Key.Substring(19));
									
					// Store ID for Edit screen
					sessionManager.SystemParameterCode = Value.ToString();
					
					// Call out to Edit screen
                    return RedirectToAction("Edit", "SystemParameter", new { code = Value });

                }
            }

            // Return to the Screen
            return View(model);
        }

        #endregion
		
		#region Private methods
		
        private void SetFlagsFalse(SystemParameterVM model)
        {
            model.IsDeleteConfirmed = "False";
            model.IsExitConfirmed = "False";
            model.IsNewConfirmed = "False";

            //Stop the binder resetting the posted values
            ModelState.Remove("IsDeleteConfirmed");
            ModelState.Remove("IsExitConfirmed");
            ModelState.Remove("IsNewConfirmed");
        }

        private void ResolveFieldCodesToFieldNamesUsingLists(SystemParameterVM model)
        {
			//TODO:
        }

        /// <summary>
        /// Private method to merge in the model 
        /// </summary>
        /// <returns></returns>
        private SystemParameterVM GetUpdatedModel()
        {
            SystemParameterVM model = new SystemParameterVM();
            RepopulateListsFromCacheSession(model);
            model.Message = "";

            if (sessionManager.CurrentSystemParameter != null)
            {
                model.SystemParameterItem = sessionManager.CurrentSystemParameter;
            }

            //***************************************NEED WHITE LIST ---- BLACK LIST ------ TO PREVENT OVERPOSTING **************************
            bool result = TryUpdateModel(model);//This also validates and sets ModelState
            //*******************************************************************************************************************************
            if (sessionManager.CurrentSystemParameter != null)
            {
                //*****************************************PREVENT OVER POSTING ATTACKS******************************************************
                //Get the values for read only fields from session
                MergeNewValuesWithOriginal(model.SystemParameterItem);
                //***************************************************************************************************************************
            }

            SetAccessContext(model);

            return model;
        }
		
        private SystemParameterVM ConvertSystemParameterDC(SystemParameterVMDC returnedObject)
        {
            SystemParameterVM model = new SystemParameterVM();
            
			// Map SystemParameter Item
			model.SystemParameterItem = Mapper.Map<SystemParameterDC, SystemParameterModel>(returnedObject.SystemParameterItem);
            
			// Map lookup data lists
        
            return model;
        }
		
		private void RepopulateListsFromCacheSession(SystemParameterVM model)
        {
			// Populate cached lists if they are empty. Will invoke service call
            SystemParameterLookupListsCacheObject CachedLists = cacheManager.SystemParameterListCache;

			// Retrieve any cached lists to model
   
        }

        private void MergeNewValuesWithOriginal(SystemParameterModel modelFromView)
        {
            //***************************The values that are display only will not be posted back so need to get them from session**************************

            SystemParameterModel OriginalValuesFromSession = sessionManager.CurrentSystemParameter;

        }
		
		private void SetAccessContext(SystemParameterVM model)
        {
            //Decide on access context
            if (null == model.SystemParameterItem || model.SystemParameterItem.Code == Guid.Empty)
            {
				// Create context
                model.AccessContext = SystemParameterAccessContext.Create;
            }
            else
            {
				// Edit context
                model.AccessContext = SystemParameterAccessContext.Edit;
            }
        }
		
		private void DetermineIsDirty(SystemParameterVM model)
        {
            //Compare the SystemParameter to the original session
            if (model.SystemParameterItem.PublicInstancePropertiesEqual(sessionManager.SystemParameterServiceVersion, "RowIdentifier"))
            {
                model.IsViewDirty = false;
            }
            else
            {
                model.IsViewDirty = true;
            }

        }
        #endregion
       
    }
}
