ALTER DATABASE [$(DatabaseName)]
    ADD LOG FILE (NAME = [ADepUCB_log], FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL10_50.ADEPDEV\MSSQL\DATA\AdepUcb_1.ldf', SIZE = 321088 KB, MAXSIZE = 2097152 MB, FILEGROWTH = 10 %);



