ALTER DATABASE [$(DatabaseName)]
    ADD FILE (NAME = [ADepUCB], FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL10_50.ADEPDEV\MSSQL\DATA\AdepUcb.mdf', SIZE = 212992 KB, FILEGROWTH = 1024 KB) TO FILEGROUP [PRIMARY];



