//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace Dwp.Adep.Ucb.DataServices.Models
{
    [MetadataTypeAttribute(typeof(ADRoleLookup.ADRoleLookupMetadata))]
    public partial class ADRoleLookup : IADRoleLookup
    {
    	public partial class ADRoleLookupMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    	
    		[Association("FK_ADRoleLookup_Role", "RoleCode", "Code", IsForeignKey = true)]
    		public virtual Role Role
    		{get; set;}
    
    	
    		[Association("FK_ADRoleLookup_Organisation_Security", "SecurityLabel", "Code", IsForeignKey = true)]
    		public virtual Organisation Organisation
    		{get; set;}
    
    		}
    }
}
