//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace Dwp.Adep.Ucb.DataServices.Models
{
    public partial class ControlMeasure : IAuditable, IActiveAware 
    {
        #region Primitive Properties
    
        public virtual System.Guid Code
        {
            get;
            set;
        }
    
        public virtual string ControlMeasureDescription
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual byte[] RowIdentifier
        {
            get;
            set;
        }
    
        public virtual int ReviewPeriod
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<CustomerControlMeasure> CustomerControlMeasure
        {
            get
            {
                if (_customerControlMeasure == null)
                {
                    var newCollection = new FixupCollection<CustomerControlMeasure>();
                    newCollection.CollectionChanged += FixupCustomerControlMeasure;
                    _customerControlMeasure = newCollection;
                }
                return _customerControlMeasure;
            }
            set
            {
                if (!ReferenceEquals(_customerControlMeasure, value))
                {
                    var previousValue = _customerControlMeasure as FixupCollection<CustomerControlMeasure>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCustomerControlMeasure;
                    }
                    _customerControlMeasure = value;
                    var newValue = value as FixupCollection<CustomerControlMeasure>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCustomerControlMeasure;
                    }
                }
            }
        }
        private ICollection<CustomerControlMeasure> _customerControlMeasure;

        #endregion
        #region Association Fixup
    
        private void FixupCustomerControlMeasure(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CustomerControlMeasure item in e.NewItems)
                {
                    item.ControlMeasure = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CustomerControlMeasure item in e.OldItems)
                {
                    if (ReferenceEquals(item.ControlMeasure, this))
                    {
                        item.ControlMeasure = null;
                    }
                }
            }
        }

        #endregion
    }
}
