//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace Dwp.Adep.Ucb.DataServices.Models
{
    [MetadataTypeAttribute(typeof(CustomerContingencyArrangement.CustomerContingencyArrangementMetadata))]
    public partial class CustomerContingencyArrangement : ICustomerContingencyArrangement
    {
    	public partial class CustomerContingencyArrangementMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    	
    		[Association("FK_CustomerContingencyArrangement_Customer", "CustomerCode", "Code", IsForeignKey = true)]
    		public virtual Customer Customer
    		{get; set;}
    
    	
    		[Association("FK_CustomerContingencyArrangement_ContingencyArrangement", "ContingencyArrangementCode", "Code", IsForeignKey = true)]
    		public virtual ContingencyArrangement ContingencyArrangement
    		{get; set;}
    
    		}
    }
}
