//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace Dwp.Adep.Ucb.DataServices.Models
{
    public partial class CustomerControlMeasure : IAuditable
    {
        #region Primitive Properties
    
        public virtual System.Guid Code
        {
            get;
            set;
        }
    
        public virtual System.Guid CustomerCode
        {
            get { return _customerCode; }
            set
            {
                if (_customerCode != value)
                {
                    if (Customer != null && Customer.Code != value)
                    {
                        Customer = null;
                    }
                    _customerCode = value;
                }
            }
        }
        private System.Guid _customerCode;
    
        public virtual System.Guid ControlMeasureCode
        {
            get { return _controlMeasureCode; }
            set
            {
                if (_controlMeasureCode != value)
                {
                    if (ControlMeasure != null && ControlMeasure.Code != value)
                    {
                        ControlMeasure = null;
                    }
                    _controlMeasureCode = value;
                }
            }
        }
        private System.Guid _controlMeasureCode;
    
        public virtual byte[] RowIdentifier
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ControlMeasure ControlMeasure
        {
            get { return _controlMeasure; }
            set
            {
                if (!ReferenceEquals(_controlMeasure, value))
                {
                    var previousValue = _controlMeasure;
                    _controlMeasure = value;
                    FixupControlMeasure(previousValue);
                }
            }
        }
        private ControlMeasure _controlMeasure;
    
        public virtual Customer Customer
        {
            get { return _customer; }
            set
            {
                if (!ReferenceEquals(_customer, value))
                {
                    var previousValue = _customer;
                    _customer = value;
                    FixupCustomer(previousValue);
                }
            }
        }
        private Customer _customer;

        #endregion
        #region Association Fixup
    
        private void FixupControlMeasure(ControlMeasure previousValue)
        {
            if (previousValue != null && previousValue.CustomerControlMeasure.Contains(this))
            {
                previousValue.CustomerControlMeasure.Remove(this);
            }
    
            if (ControlMeasure != null)
            {
                if (!ControlMeasure.CustomerControlMeasure.Contains(this))
                {
                    ControlMeasure.CustomerControlMeasure.Add(this);
                }
                if (ControlMeasureCode != ControlMeasure.Code)
                {
                    ControlMeasureCode = ControlMeasure.Code;
                }
            }
        }
    
        private void FixupCustomer(Customer previousValue)
        {
            if (previousValue != null && previousValue.CustomerControlMeasure.Contains(this))
            {
                previousValue.CustomerControlMeasure.Remove(this);
            }
    
            if (Customer != null)
            {
                if (!Customer.CustomerControlMeasure.Contains(this))
                {
                    Customer.CustomerControlMeasure.Add(this);
                }
                if (CustomerCode != Customer.Code)
                {
                    CustomerCode = Customer.Code;
                }
            }
        }

        #endregion
    }
}
