//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace Dwp.Adep.Ucb.DataServices.Models
{
    [MetadataTypeAttribute(typeof(Customer.CustomerMetadata))]
    public partial class Customer : ICustomer
    {
    	public partial class CustomerMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    	
    		[Association("FK_IncidentControlMeasure_Customer", "Code", "CustomerCode", IsForeignKey = false)]
    		public virtual ICollection<CustomerControlMeasure> CustomerControlMeasure
    		{get; set;}
    
    	
    		[Association("FK_LinkedCustomer_Customer", "Code", "Customer1Code", IsForeignKey = false)]
    		public virtual ICollection<LinkedCustomer> LinkedCustomer
    		{get; set;}
    
    	
    		[Association("FK_LinkedCustomer_Customer1", "Code", "Customer2Code", IsForeignKey = false)]
    		public virtual ICollection<LinkedCustomer> LinkedCustomer1
    		{get; set;}
    
    	
    		[Association("FK_CustomerContingencyArrangement_Customer", "Code", "CustomerCode", IsForeignKey = false)]
    		public virtual ICollection<CustomerContingencyArrangement> CustomerContingencyArrangement
    		{get; set;}
    
    	
    		[Association("FK_Customer_RelationshipToCustomer", "RelationshipToCustomerCode", "Code", IsForeignKey = true)]
    		public virtual RelationshipToCustomer RelationshipToCustomer
    		{get; set;}
    
    	
    		[Association("FK_Incident_Customer", "Code", "CustomerCode", IsForeignKey = false)]
    		public virtual ICollection<Incident> Incident
    		{get; set;}
    
    		}
    }
}
