//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace Dwp.Adep.Ucb.DataServices.Models
{
    [MetadataTypeAttribute(typeof(Incident.IncidentMetadata))]
    public partial class Incident : IIncident
    {
    	public partial class IncidentMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    	
    		[Association("FK_Incident_AbuseType", "AbuseTypeCode", "Code", IsForeignKey = true)]
    		public virtual AbuseType AbuseType
    		{get; set;}
    
    	
    		[Association("FK_Attachment_Incident", "Code", "IncidentCode", IsForeignKey = false)]
    		public virtual ICollection<Attachment> Attachment
    		{get; set;}
    
    	
    		[Association("FK_Incident_Customer", "CustomerCode", "Code", IsForeignKey = true)]
    		public virtual Customer Customer
    		{get; set;}
    
    	
    		[Association("FK_Incident_EventLeadingToIncident", "EventLeadingToIncidentCode", "Code", IsForeignKey = true)]
    		public virtual EventLeadingToIncident EventLeadingToIncident
    		{get; set;}
    
    	
    		[Association("FK_Incident_DeficienciesNarrative", "DeficienciesNarrativeCode", "Code", IsForeignKey = true)]
    		public virtual Narrative Narrative
    		{get; set;}
    
    	
    		[Association("FK_Incident_FurtherInfoNarrative", "FurtherInfoNarrativeCode", "Code", IsForeignKey = true)]
    		public virtual Narrative Narrative1
    		{get; set;}
    
    	
    		[Association("FK_Incident_IncidentCategory", "IncidentCategoryCode", "Code", IsForeignKey = true)]
    		public virtual IncidentCategory IncidentCategory
    		{get; set;}
    
    	
    		[Association("FK_Incident_IncidentDetail", "IncidentDetailsCode", "Code", IsForeignKey = true)]
    		public virtual IncidentDetail IncidentDetail
    		{get; set;}
    
    	
    		[Association("FK_Incident_IncidentLocation", "IncidentLocationCode", "Code", IsForeignKey = true)]
    		public virtual IncidentLocation IncidentLocation
    		{get; set;}
    
    	
    		[Association("FK_Incident_IncidentNarrative", "IncidentNarrativeCode", "Code", IsForeignKey = true)]
    		public virtual Narrative Narrative2
    		{get; set;}
    
    	
    		[Association("FK_Incident_IncidentType", "IncidentTypeCode", "Code", IsForeignKey = true)]
    		public virtual IncidentType IncidentType
    		{get; set;}
    
    	
    		[Association("FK_Incident_JobRole", "JobRoleCode", "Code", IsForeignKey = true)]
    		public virtual JobRole JobRole
    		{get; set;}
    
    	
    		[Association("FK_Incident_LineManagerNarrative", "LineManagerNarrativeCode", "Code", IsForeignKey = true)]
    		public virtual Narrative Narrative3
    		{get; set;}
    
    	
    		[Association("FK_Incident_Referrer", "ReferrerCode", "Code", IsForeignKey = true)]
    		public virtual Referrer Referrer
    		{get; set;}
    
    	
    		[Association("FK_Incident_ReviewActionNarrative", "ReviewActionNarrativeCode", "Code", IsForeignKey = true)]
    		public virtual Narrative Narrative4
    		{get; set;}
    
    	
    		[Association("FK_Incident_Site", "SiteCode", "Code", IsForeignKey = true)]
    		public virtual Site Site
    		{get; set;}
    
    	
    		[Association("FK_Incident_Site1", "StaffMemberHomeOfficeSiteCode", "Code", IsForeignKey = true)]
    		public virtual Site Site1
    		{get; set;}
    
    	
    		[Association("FK_Incident_Staff", "CurrentOwnerStaffCode", "Code", IsForeignKey = true)]
    		public virtual Staff Staff
    		{get; set;}
    
    	
    		[Association("FK_IncidentInterestedParty_Incident", "Code", "IncidentCode", IsForeignKey = false)]
    		public virtual ICollection<IncidentInterestedParty> IncidentInterestedParty
    		{get; set;}
    
    	
    		[Association("FK_IncidentLink_Incident", "Code", "IncidentCode", IsForeignKey = false)]
    		public virtual ICollection<IncidentLink> IncidentLink
    		{get; set;}
    
    	
    		[Association("FK_IncidentLink_Incident1", "Code", "LinkedIncidentCode", IsForeignKey = false)]
    		public virtual ICollection<IncidentLink> IncidentLink1
    		{get; set;}
    
    	
    		[Association("FK_IncidentSystemMarked_Incident", "Code", "IncidentCode", IsForeignKey = false)]
    		public virtual ICollection<IncidentSystemMarked> IncidentSystemMarked
    		{get; set;}
    
    	
    		[Association("FK_IncidentUpdateEvent_Incident", "Code", "IncidentCode", IsForeignKey = false)]
    		public virtual ICollection<IncidentUpdateEvent> IncidentUpdateEvent
    		{get; set;}
    
    		}
    }
}
