//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace Dwp.Adep.Ucb.DataServices.Models
{
    [MetadataTypeAttribute(typeof(IncidentLink.IncidentLinkMetadata))]
    public partial class IncidentLink : IIncidentLink
    {
    	public partial class IncidentLinkMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    	
    		[Association("FK_IncidentLink_Incident", "IncidentCode", "Code", IsForeignKey = true)]
    		public virtual Incident Incident
    		{get; set;}
    
    	
    		[Association("FK_IncidentLink_Incident1", "LinkedIncidentCode", "Code", IsForeignKey = true)]
    		public virtual Incident Incident1
    		{get; set;}
    
    		}
    }
}
