//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace Dwp.Adep.Ucb.DataServices.Models
{
    [MetadataTypeAttribute(typeof(LinkedCustomer.LinkedCustomerMetadata))]
    public partial class LinkedCustomer : ILinkedCustomer
    {
    	public partial class LinkedCustomerMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    	
    		[Association("FK_LinkedCustomer_Customer", "Customer1Code", "Code", IsForeignKey = true)]
    		public virtual Customer Customer
    		{get; set;}
    
    	
    		[Association("FK_LinkedCustomer_Customer1", "Customer2Code", "Code", IsForeignKey = true)]
    		public virtual Customer Customer1
    		{get; set;}
    
    		}
    }
}
