//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace Dwp.Adep.Ucb.DataServices.Models
{
    [MetadataTypeAttribute(typeof(Role.RoleMetadata))]
    public partial class Role : IRole
    {
    	public partial class RoleMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    	
    		[Association("FK_ADRoleLookup_Role", "Code", "RoleCode", IsForeignKey = false)]
    		public virtual ICollection<ADRoleLookup> ADRoleLookup
    		{get; set;}
    
    	
    		[Association("FK_Role_Application", "ApplicationCode", "Code", IsForeignKey = true)]
    		public virtual Application Application
    		{get; set;}
    
    	
    		[Association("FK_Role_Organisation", "SecurityLabel", "Code", IsForeignKey = true)]
    		public virtual Organisation Organisation
    		{get; set;}
    
    	
    		[Association("FK_Role_Organisation_Security", "SecurityLabel", "Code", IsForeignKey = true)]
    		public virtual Organisation Organisation1
    		{get; set;}
    
    		}
    }
}
