CREATE TABLE [dbo].[Incident] (
    [Code]                           UNIQUEIDENTIFIER NOT NULL,
    [IncidentID]                     INT              IDENTITY (1, 1) NOT NULL,
    [IncidentStatus]                 NVARCHAR (50)    NOT NULL,
    [StaffMemberTitle]               NVARCHAR (50)    NOT NULL,
    [StaffMemberOtherTitle]          NVARCHAR (50)    NULL,
    [StaffMemberFirstName]           NVARCHAR (50)    NOT NULL,
    [StaffMemberLastName]            NVARCHAR (50)    NOT NULL,
    [JobRoleCode]                    UNIQUEIDENTIFIER NOT NULL,
    [StaffMemberBusinessCode]        UNIQUEIDENTIFIER NOT NULL,
    [StaffMemberBusinessAreaCode]    UNIQUEIDENTIFIER NOT NULL,
    [StaffMemberHomeOfficeCode]      UNIQUEIDENTIFIER NOT NULL,
    [StaffMemberHomeOfficeSiteCode]  UNIQUEIDENTIFIER NOT NULL,
    [IsStaffHadAppropriateTraining]  NVARCHAR (10)    NULL,
    [StaffMemberYearsInCurrentPost]  INT              NULL,
    [StaffMemberMonthsInCurrentRole] INT              NULL,
    [ManagerFirstName]               NVARCHAR (50)    NOT NULL,
    [ManagerLastName]                NVARCHAR (50)    NOT NULL,
    [IncidentDate]                   DATETIME         NOT NULL,
    [FiscalYear]                     INT              NOT NULL,
    [FiscalQuarter]                  INT              NOT NULL,
    [FiscalMonth]                    INT              NOT NULL,
    [FiscalMonthAsText]              NVARCHAR (20)    NULL,
    [IncidentTime]                   NVARCHAR (5)     NULL,
    [CustomerCode]                   UNIQUEIDENTIFIER NULL,
    [IsOthersPresent]                BIT              NOT NULL,
    [OthersPresent]                  NVARCHAR (250)   NULL,
    [EventLeadingToIncidentCode]     UNIQUEIDENTIFIER NULL,
    [IncidentLocationCode]           UNIQUEIDENTIFIER NOT NULL,
    [IncidentCategoryCode]           UNIQUEIDENTIFIER NOT NULL,
    [IncidentTypeCode]               UNIQUEIDENTIFIER NOT NULL,
    [IncidentDetailsCode]            UNIQUEIDENTIFIER NULL,
    [AbuseTypeCode]                  UNIQUEIDENTIFIER NULL,
    [IncidentNarrativeCode]          UNIQUEIDENTIFIER NOT NULL,
    [IsLineManageFastTrack]          BIT              NULL,
    [IsLineManagerRIDDOR]            BIT              NULL,
    [IsPoliceCalled]                 BIT              NULL,
    [HasLineManagerReadReport]       BIT              NULL,
    [LineManagerNarrativeCode]       UNIQUEIDENTIFIER NULL,
    [IsNominatedFastTrack]           BIT              NULL,
    [IsNominatedRIDDOR]              BIT              NULL,
    [IsOralWarning]                  BIT              NULL,
    [OralWarningDate]                DATE             NULL,
    [IsWrittenWarning]               BIT              NULL,
    [WrittenWarningDate]             DATE             NULL,
    [IsAssailantInterviewed]         BIT              NULL,
    [AssailantInterviewedDate]       DATE             NULL,
    [IsSolicitorLetter]              BIT              NULL,
    [SolicitorLetterDate]            DATE             NULL,
    [IsBanningOrder]                 BIT              NULL,
    [BanningOrderRequestedDate]      DATE             NULL,
    [FurtherInfoNarrativeCode]       UNIQUEIDENTIFIER NULL,
    [IsDeficienciesInProcess]        BIT              NULL,
    [IsImplementControlMeasures]     BIT              NULL,
    [NamedOfficer]                   NVARCHAR (100)   NULL,
    [TelephoneContactNumber]         NVARCHAR (50)    NULL,
    [IsITMarkersSet]                 BIT              NULL,
    [IsPapersMarked]                 BIT              NULL,
    [IsNotifiedParties]              BIT              NULL,
    [ReviewDate]                     DATE             NULL,
    [IsPreviousEvidenceReviewed]     BIT              NULL,
    [IsPreviousPartiesNotified]      BIT              NULL,
    [IsRepeatBehaviour]              BIT              NULL,
    [IsControlMeasuresStillApply]    BIT              NULL,
    [OrganisationCode]               UNIQUEIDENTIFIER NOT NULL,
    [SiteCode]                       UNIQUEIDENTIFIER NOT NULL,
    [NumberOfRecords]                INT              NULL,
    [RowIdentifier]                  TIMESTAMP        NOT NULL,
    [DeficienciesNarrativeCode]      UNIQUEIDENTIFIER NULL
);



