//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using Dwp.Adep.Ucb.ResourceLibrary;
using UcbWeb.DataAnnotation;

namespace UcbWeb.Models
{
    [MetadataTypeAttribute(typeof(CustomerContingencyArrangementModel.CustomerContingencyArrangementModelMetadata))]
    public partial class CustomerContingencyArrangementModel
    {
    	public partial class CustomerContingencyArrangementModelMetadata
    	{
    		[Key]
    		[Required(ErrorMessageResourceName = "VAL_REQUIRED", ErrorMessageResourceType = typeof(Resources))]
    		[Tooltip("TOOLTIP_CUSTOMERCONTINGENCYARRANGEMENT_CODE", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_CUSTOMERCONTINGENCYARRANGEMENT_CODE", ResourceType=typeof(Resources))]
    		public System.Guid Code {get; set;}
    
      		[Required(ErrorMessageResourceName = "VAL_REQUIRED", ErrorMessageResourceType = typeof(Resources))]
    		[Tooltip("TOOLTIP_CUSTOMERCONTINGENCYARRANGEMENT_CUSTOMERCODE", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_CUSTOMERCONTINGENCYARRANGEMENT_CUSTOMERCODE", ResourceType=typeof(Resources))]
    		public System.Guid CustomerCode {get; set;}
    
      		[Required(ErrorMessageResourceName = "VAL_REQUIRED", ErrorMessageResourceType = typeof(Resources))]
    		[Tooltip("TOOLTIP_CUSTOMERCONTINGENCYARRANGEMENT_CONTINGENCYARRANGEMENTCODE", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_CUSTOMERCONTINGENCYARRANGEMENT_CONTINGENCYARRANGEMENTCODE", ResourceType=typeof(Resources))]
    		public System.Guid ContingencyArrangementCode {get; set;}
    
        }
    }
}
