//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using Dwp.Adep.Ucb.ResourceLibrary;
using UcbWeb.DataAnnotation;

namespace UcbWeb.Models
{
    [MetadataTypeAttribute(typeof(OrganisationHierarchyModel.OrganisationHierarchyModelMetadata))]
    public partial class OrganisationHierarchyModel
    {
    	public partial class OrganisationHierarchyModelMetadata
    	{
    		[Key]
    		[Required(ErrorMessageResourceName = "VAL_REQUIRED", ErrorMessageResourceType = typeof(Resources))]
    		[Tooltip("TOOLTIP_ORGANISATIONHIERARCHY_CODE", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_ORGANISATIONHIERARCHY_CODE", ResourceType=typeof(Resources))]
    		public System.Guid Code {get; set;}
    
      		[Required(ErrorMessageResourceName = "VAL_REQUIRED", ErrorMessageResourceType = typeof(Resources))]
    		[Tooltip("TOOLTIP_ORGANISATIONHIERARCHY_ANCESTORORGANISATIONCODE", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_ORGANISATIONHIERARCHY_ANCESTORORGANISATIONCODE", ResourceType=typeof(Resources))]
    		public System.Guid AncestorOrganisationCode {get; set;}
    
      		[Required(ErrorMessageResourceName = "VAL_REQUIRED", ErrorMessageResourceType = typeof(Resources))]
    		[Tooltip("TOOLTIP_ORGANISATIONHIERARCHY_ORGANISATIONCODE", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_ORGANISATIONHIERARCHY_ORGANISATIONCODE", ResourceType=typeof(Resources))]
    		public System.Guid OrganisationCode {get; set;}
    
      		[Required(ErrorMessageResourceName = "VAL_REQUIRED", ErrorMessageResourceType = typeof(Resources))]
    		[Tooltip("TOOLTIP_ORGANISATIONHIERARCHY_IMMEDIATEPARENT", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_ORGANISATIONHIERARCHY_IMMEDIATEPARENT", ResourceType=typeof(Resources))]
    		public bool ImmediateParent {get; set;}
    
      		[Tooltip("TOOLTIP_ORGANISATIONHIERARCHY_HOPSBETWEENORGANDANCESTOR", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_ORGANISATIONHIERARCHY_HOPSBETWEENORGANDANCESTOR", ResourceType=typeof(Resources))]
    		public Nullable<int> HopsBetweenOrgAndAncestor {get; set;}
    
      		[Required(ErrorMessageResourceName = "VAL_REQUIRED", ErrorMessageResourceType = typeof(Resources))]
    		[Tooltip("TOOLTIP_ORGANISATIONHIERARCHY_ISACTIVE", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_ORGANISATIONHIERARCHY_ISACTIVE", ResourceType=typeof(Resources))]
    		public bool IsActive {get; set;}
    
        }
    }
}
