ALTER TABLE [dbo].[ControlMeasure]
    ADD CONSTRAINT [UK_ControlMeasure_ControlMeasureDescription] UNIQUE NONCLUSTERED ([ControlMeasureDescription] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

