//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace Dwp.Adep.Ucb.WebServices.DataContracts
{
    [DataContract]
    public partial class StaffDC
    {
    
    	[DataMember]
        public System.Guid Code
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public string StaffNumber
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public string LastName
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public string FirstName
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public System.Guid GradeCode
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public bool IsActive
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public byte[] RowIdentifier
        {
    	    get;
            set;
        }
    }
}
