//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace Dwp.Adep.Ucb.WebServices.DataContracts
{
    [DataContract]
    public partial class StandardReportSearchCriteriaDC
    {
    
    	[DataMember]
        public virtual string ReportName
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual string ReportDescription
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual System.Guid ReportCategoryCode
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual string ReportCategory
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual int SortOrder
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual string ReportUrl
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual bool IsPrintable
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual bool IsExportable
        {
    	    get;
            set;
        }
    }
}
