//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using UcbWeb.Models;
using System.Linq;
using UcbWeb.DataAnnotation;
using Dwp.Adep.Ucb.ResourceLibrary;

namespace UcbWeb.ViewModels
{
    public partial class SiteVM : IValidatableObject
    {
        public SiteModel SiteItem { get; set; }

        [Tooltip("TOOLTIP_SITE_NOMINATEDMANAGERFIRSTNAMESEARCH", ResourceType = typeof(Resources))]
        [Display(Name = "LABEL_SITE_NOMINATEDMANAGERFIRSTNAMESEARCH", ResourceType = typeof(Resources))]
        public string NominatedManagerFirstNameSearch { get; set; }

        [Tooltip("TOOLTIP_SITE_NOMINATEDMANAGERLASTNAMESEARCH", ResourceType = typeof(Resources))]
        [Display(Name = "LABEL_SITE_NOMINATEDMANAGERLASTNAMESEARCH", ResourceType = typeof(Resources))]
        public string NominatedManagerLastNameSearch { get; set; }

        [Required(ErrorMessageResourceName = "VAL_REQUIRED", ErrorMessageResourceType = typeof(Resources))]
        [Tooltip("TOOLTIP_SITE_NOMINATEDMANAGER", ResourceType = typeof(Resources))]
        [Display(Name = "LABEL_SITE_NOMINATEDMANAGER", ResourceType = typeof(Resources))]
        public List<StaffModel> NominatedManagerSearchList { get; set; }

        [Required(ErrorMessageResourceName = "VAL_REQUIRED", ErrorMessageResourceType = typeof(Resources))]
        [Tooltip("TOOLTIP_SITE_NOMINATEDMANAGER", ResourceType = typeof(Resources))]
        [Display(Name = "LABEL_SITE_NOMINATEDMANAGER", ResourceType = typeof(Resources))]
        public string NominatedManagerCode { get; set; }

        [Tooltip("TOOLTIP_SITE_DEPUTYNOMINATEDMANAGERFIRSTNAMESEARCH", ResourceType = typeof(Resources))]
        [Display(Name = "LABEL_SITE_DEPUTYNOMINATEDMANAGERFIRSTNAMESEARCH", ResourceType = typeof(Resources))]
        public string DeputyNominatedManagerFirstNameSearch { get; set; }

        [Tooltip("TOOLTIP_SITE_DEPUTYNOMINATEDMANAGERLASTNAMESEARCH", ResourceType = typeof(Resources))]
        [Display(Name = "LABEL_SITE_DEPUTYNOMINATEDMANAGERLASTNAMESEARCH", ResourceType = typeof(Resources))]
        public string DeputyNominatedManagerLastNameSearch { get; set; }


         [Tooltip("TOOLTIP_SITE_DEPUTYNOMINATEDMANAGERSELECTLIST", ResourceType = typeof(Resources))]
         [Display(Name = "LABEL_SITE_DEPUTYNOMINATEDMANAGERSELECTLIST", ResourceType = typeof(Resources))]
        public List<StaffModel> DeputyNominatedManagerSearchList { get; set; }

         [Tooltip("TOOLTIP_SITE_DEPUTYNOMINATEDMANAGERLIST", ResourceType = typeof(Resources))]
         [Display(Name = "LABEL_SITE_DEPUTYNOMINATEDMANAGERLIST", ResourceType = typeof(Resources))]
         public List<StaffModel> DeputyNominatedManagerList { get; set; }

         public string DeputyNominatedManagerCode { get; set; }

        public string Message { get; set; }

        public string IsDeleteConfirmed { get; set; }
        public string IsExitConfirmed { get; set; }
        public string IsNewConfirmed { get; set; }
        public bool IsViewDirty { get; set; }

        public SiteAccessContext AccessContext { get; set; }


        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            List<ValidationResult> results = new List<ValidationResult>();
            Guid NominatedManager = Guid.Empty;
            if (NominatedManagerCode != null)
            {
                NominatedManager = Guid.Parse(NominatedManagerCode);
                var NominatedManagerInDeputyList = DeputyNominatedManagerList.SingleOrDefault(x => x.Code == NominatedManager);
                if (NominatedManagerInDeputyList != null)
                {
                    results.Add(new ValidationResult(Resources.VAL_NOMINATEDMANAGER_IN_DEPUTY_LIST, new List<string>() { "NominatedManagerCode" }));
                }
            }
            return results;
        }
    }

    public enum SiteAccessContext
    {
        Create,
        View,
        Edit
    }
}
